import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "@/styles/globals.css";
import Layout from "@/components/layout";

const font = Noto_Sans_JP({
   subsets: ["latin", "cyrillic"],
   variable: "--font-primary",
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={`${font.variable} antialiased`}>
            <Layout>{children}</Layout>
         </body>
      </html>
   );
}
