import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "@/styles/globals.css";
import Layout from "@/components/layout";
import Provider from "@/store/provider";

const font = Noto_Sans_JP({
   subsets: ["latin", "cyrillic"],
   variable: "--font-primary",
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <Provider>
         <html lang="en">
            <body className={`${font.variable} antialiased`}>
               <Layout>
                  <main className="min-h-screen">{children}</main>
               </Layout>
            </body>
         </html>
      </Provider>
   );
}
